image: # Replace with your Docker image name or leave it blank to use the Dockerfile.

stages:
  - build
  - test
  - deploy

variables:
  ANDROID_COMPILE_SDK: "31"
  ANDROID_BUILD_TOOLS: "31.0.0"
  ANDROID_TARGET_SDK: "31"

before_script:
  - export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

build:
  stage: build
  tags:
    - make
  script:
    - echo "Building the React Native Android App"
    - cd android
    - ./gradlew assembleRelease  # or ./gradlew assembleDebug
  artifacts:
    paths:
      - android/app/build/outputs/apk/release/app-release.apk  # Adjust according to your project structure
      - android/app/build/outputs/apk/debug/app-debug.apk  # If you're building debug APK

test:
  stage: test
  tags:
    - make
  script:
    - echo "Running tests"
    - npm test  # Adjust according to your testing setup

deploy:
  stage: deploy
  tags:
    - make
  script:
    - echo "Deploying to your target environment"
    # Add your deployment commands here (e.g., upload APK to Firebase, Play Store, etc.)
  only:
    - main  # Adjust this based on your branching strategy
