# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:android)

platform :android do
  desc "Build the app as an AAB"
  lane :build_aab do
    gradle(
      task: "bundle", # This will create the .aab file
      build_type: "Release"
    )
  end

  desc "Deploy a new version to internal testing on Google Play"
  lane :internal_testing do
    build_aab
    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end