name: Build Android APK

on:
  push:
    branches:
      - main
        


jobs:
  build:
    runs-on: android
    steps:
      - name: Setup Environment for job 
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Installing Dependencies
        run: npm install
        
      - name: Build SampleApplication
        run: |
          cd android && chmod +x ./gradlew
          ./gradlew assembleRelease