name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    if: contains(github.event.head_commit.message, 'github')
    runs-on: android
    steps:
      - name: Setup Environment for job 
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Installing Dependencies
        run: npm install


      - name: Run Android Line
        run: cd android && ./gradlew lint
        
      - name: Run Unit Tests
        run: cd android && ./gradlew test

      - name: Build Application
        run: |
          cd android && ./gradlew assembleRelease

      - name: .aab realase build
        run: cd android &&  ./gradlew bundleRelease && ls -latr

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk  
          path: android/app/build/outputs/apk/release/app-release.apk
          retention-days: 1
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: android/app/build/outputs/bundle/release/app-release.aab
          retention-days: 1


          

      # Create a GitHub Release and upload the APK/AAB files
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
        with:
          tag_name: ${{ github.ref}}
          release_name: Release ${{ github.ref}}
          draft: false
          prerelease: false

      # Upload APK to GitHub Release
      - name: Upload APK to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: android/app/build/outputs/apk/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive

      # Upload AAB to GitHub Release
      - name: Upload AAB to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: android/app/build/outputs/bundle/release/app-release.aab
          asset_name: app-release.aab
          asset_content_type: application/octet-stream