name: Build Android APK

on:
  push:
    branches:
      - main
        


jobs:
  build:
    runs-on: android
    steps:
      - name: Setup Environment for job 
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Installing Dependencies
        run: npm install


      - name: Run Android Line
        run: ./gradlew lint
      - name: Run Unit Tests
        run: ./gradlew test
        
      - name: Build SampleApplication
        run: |
          cd android && chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk  
          path: android/app/build/outputs/apk/release/app-release.apk
          retention-days: 1